
name:  Automatic Steps for Notekeeper

on:
  push:
    branches: ["main"]

env:
  JAVA_VERSION: '17'                       

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}

    - name: 'Run it...'
      shell: 'bash'
      run: |
        java Main.java >> out
        cat out 